name: dialog_flowtter
description: A Flutter implementation of DialogFlow, improved
version: 0.1.0
author: ElZombieIsra
homepage: https://github.com/Deimos-Applications/dialog_flowtter
repository: https://github.com/Deimos-Applications/dialog_flowtter
issue_tracker: https://github.com/Deimos-Applications/dialog_flowtter/issues

environment:
    sdk: ">=2.7.0 <3.0.0"
    flutter: ">=1.17.0 <2.0.0"

dependencies:
    flutter:
        sdk: flutter
    googleapis_auth: ^0.2.12
    equatable: ^1.2.3
    json_annotation: ^3.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    effective_dart: ^1.0.0
    build_runner: ^1.10.1
    json_serializable: ^3.2.5
