name: dialog_flowtter
description: A new Flutter package project.
version: 0.0.1
author: ElZombieIsra
homepage: https://www.deimos.app

environment:
    sdk: ">=2.7.0 <3.0.0"
    flutter: ">=1.17.0 <2.0.0"

dependencies:
    flutter:
        sdk: flutter
    googleapis_auth: ^0.2.12
    equatable: ^1.2.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    effective_dart: ^1.0.0
flutter:
